// Cracks hash string generated by crypt() function.
// Use hash string as an argument.
// E.g.: $ ./cracker 50cI2vYkF0YU2

#include <stdio.h>
#include <crypt.h>
#include <string.h>

#define maxPassLength 5 // Set expected max password length here

void alphabeticToNext(int letter, char kword[]);

int main(int argc, char* argv[])
{
    // Check to see that only 1 argument was input
    if (argc != 2)
    {
        printf("Usage: ./cracker hash\n");
        return 1;
    }

    // Initialize password
    char password[maxPassLength + 1] = {'\0'};
    password[0] = 'A';

    // Salt initialization
    char salt[] = {argv[1][0], argv[1][1], '\0'};

    // Probe for password
    while (password[maxPassLength] == '\0')
    {
        // Enrypt current password sample
        char *hashout = crypt(password, salt);

        if (strcmp(argv[1], hashout) == 0)
        {
            // Match found
            printf("%s\n", password);
            return 0;
        }
        else
        {
            alphabeticToNext(0, password);
        }
    }

    printf("match not found - loop limit reached\n");
    return 2;
}

// Rotates first password letter by one and after full cycle (when it was'z')
// resets to 'A' and changes next letter(s) by 1
void alphabeticToNext(int letter, char kword[])
{
    kword[letter] = kword[letter] + 1;

    if (kword[letter] == '[') // Ascii '[' == 91, follows ascii 'Z' == 90
    {
        kword[letter] = 'a'; // Ascii 'a' == 97
    }
    if (kword[letter] == '{') // Ascii '{' == 123, follows ascii 'z' == 122
    {
        kword[letter] = 'A'; // Ascii 'A' == 65
        alphabeticToNext(letter + 1, kword); // Rotates next password letter(s)

        // When new letter is initialized, its ascii value of 0 ('\0') changes to 1 ("Start Of Heading")
        // and must be scrolled to 'A'
        if (kword[letter + 1] == 1) // Ascii "Start of Heading"
        {
            kword[letter + 1] = 'A'; // Ascii 'A' == 65
        }
    }
}
