// Returns hash of your password generated by crypt() function.

#include <stdio.h>
#include <crypt.h>

void clearInputBuffer(void);

int main(void)
{
    char password[6] = {0};
    char salt[3] = {0};

    printf("Please type your password,\nuse alphabetic characters only, maximum 5 characters:\n");
    scanf(" %5[A-Za-z]", password);

    printf("Accepted password: %s\n", password);

    clearInputBuffer();

    printf("Please type crypt SALT,\nuse alphanumeric characters only, maximum 2 characters:\n");
    scanf(" %2[0-9A-Za-z]", salt);

    printf("Accepted salt: %s\n", salt);

    char *hash = crypt(password, salt);
    printf("Your password hash: %s\n", hash);

    return 0;

}

void clearInputBuffer(void)
{
    int c;
    while((c = fgetc( stdin )) != EOF && c != '\n')
    ;
}